/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmiRouteImport } from './routes/emi'
import { Route as FdRouteImport } from './routes/fd'
import { Route as LumpsumRouteImport } from './routes/lumpsum'
import { Route as NpsRouteImport } from './routes/nps'
import { Route as PpfRouteImport } from './routes/ppf'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RdRouteImport } from './routes/rd'
import { Route as SipRouteImport } from './routes/sip'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsBuyHomeVsRentIndia2026RouteImport } from './routes/blogs.buy-home-vs-rent-india-2026'
import { Route as BlogsOldVsNewTaxRegime2026CompleteGuideRouteImport } from './routes/blogs.old-vs-new-tax-regime-2026-complete-guide'
import { Route as BlogsSipVsEmiVsFdRouteImport } from './routes/blogs.sip-vs-emi-vs-fd'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmiRoute = EmiRouteImport.update({
  id: '/emi',
  path: '/emi',
  getParentRoute: () => rootRouteImport,
} as any)
const FdRoute = FdRouteImport.update({
  id: '/fd',
  path: '/fd',
  getParentRoute: () => rootRouteImport,
} as any)
const LumpsumRoute = LumpsumRouteImport.update({
  id: '/lumpsum',
  path: '/lumpsum',
  getParentRoute: () => rootRouteImport,
} as any)
const NpsRoute = NpsRouteImport.update({
  id: '/nps',
  path: '/nps',
  getParentRoute: () => rootRouteImport,
} as any)
const PpfRoute = PpfRouteImport.update({
  id: '/ppf',
  path: '/ppf',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RdRoute = RdRouteImport.update({
  id: '/rd',
  path: '/rd',
  getParentRoute: () => rootRouteImport,
} as any)
const SipRoute = SipRouteImport.update({
  id: '/sip',
  path: '/sip',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBuyHomeVsRentIndia2026Route =
  BlogsBuyHomeVsRentIndia2026RouteImport.update({
    id: '/blogs/buy-home-vs-rent-india-2026',
    path: '/blogs/buy-home-vs-rent-india-2026',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsOldVsNewTaxRegime2026CompleteGuideRoute =
  BlogsOldVsNewTaxRegime2026CompleteGuideRouteImport.update({
    id: '/blogs/old-vs-new-tax-regime-2026-complete-guide',
    path: '/blogs/old-vs-new-tax-regime-2026-complete-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogsSipVsEmiVsFdRoute = BlogsSipVsEmiVsFdRouteImport.update({
  id: '/blogs/sip-vs-emi-vs-fd',
  path: '/blogs/sip-vs-emi-vs-fd',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emi': typeof EmiRoute
  '/fd': typeof FdRoute
  '/lumpsum': typeof LumpsumRoute
  '/nps': typeof NpsRoute
  '/ppf': typeof PpfRoute
  '/privacy': typeof PrivacyRoute
  '/rd': typeof RdRoute
  '/sip': typeof SipRoute
  '/tax': typeof TaxRoute
  '/terms': typeof TermsRoute
  '/blogs/buy-home-vs-rent-india-2026': typeof BlogsBuyHomeVsRentIndia2026Route
  '/blogs/old-vs-new-tax-regime-2026-complete-guide': typeof BlogsOldVsNewTaxRegime2026CompleteGuideRoute
  '/blogs/sip-vs-emi-vs-fd': typeof BlogsSipVsEmiVsFdRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emi': typeof EmiRoute
  '/fd': typeof FdRoute
  '/lumpsum': typeof LumpsumRoute
  '/nps': typeof NpsRoute
  '/ppf': typeof PpfRoute
  '/privacy': typeof PrivacyRoute
  '/rd': typeof RdRoute
  '/sip': typeof SipRoute
  '/tax': typeof TaxRoute
  '/terms': typeof TermsRoute
  '/blogs/buy-home-vs-rent-india-2026': typeof BlogsBuyHomeVsRentIndia2026Route
  '/blogs/old-vs-new-tax-regime-2026-complete-guide': typeof BlogsOldVsNewTaxRegime2026CompleteGuideRoute
  '/blogs/sip-vs-emi-vs-fd': typeof BlogsSipVsEmiVsFdRoute
  '/blogs': typeof BlogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/emi': typeof EmiRoute
  '/fd': typeof FdRoute
  '/lumpsum': typeof LumpsumRoute
  '/nps': typeof NpsRoute
  '/ppf': typeof PpfRoute
  '/privacy': typeof PrivacyRoute
  '/rd': typeof RdRoute
  '/sip': typeof SipRoute
  '/tax': typeof TaxRoute
  '/terms': typeof TermsRoute
  '/blogs/buy-home-vs-rent-india-2026': typeof BlogsBuyHomeVsRentIndia2026Route
  '/blogs/old-vs-new-tax-regime-2026-complete-guide': typeof BlogsOldVsNewTaxRegime2026CompleteGuideRoute
  '/blogs/sip-vs-emi-vs-fd': typeof BlogsSipVsEmiVsFdRoute
  '/blogs/': typeof BlogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/emi'
    | '/fd'
    | '/lumpsum'
    | '/nps'
    | '/ppf'
    | '/privacy'
    | '/rd'
    | '/sip'
    | '/tax'
    | '/terms'
    | '/blogs/buy-home-vs-rent-india-2026'
    | '/blogs/old-vs-new-tax-regime-2026-complete-guide'
    | '/blogs/sip-vs-emi-vs-fd'
    | '/blogs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/emi'
    | '/fd'
    | '/lumpsum'
    | '/nps'
    | '/ppf'
    | '/privacy'
    | '/rd'
    | '/sip'
    | '/tax'
    | '/terms'
    | '/blogs/buy-home-vs-rent-india-2026'
    | '/blogs/old-vs-new-tax-regime-2026-complete-guide'
    | '/blogs/sip-vs-emi-vs-fd'
    | '/blogs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/emi'
    | '/fd'
    | '/lumpsum'
    | '/nps'
    | '/ppf'
    | '/privacy'
    | '/rd'
    | '/sip'
    | '/tax'
    | '/terms'
    | '/blogs/buy-home-vs-rent-india-2026'
    | '/blogs/old-vs-new-tax-regime-2026-complete-guide'
    | '/blogs/sip-vs-emi-vs-fd'
    | '/blogs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EmiRoute: typeof EmiRoute
  FdRoute: typeof FdRoute
  LumpsumRoute: typeof LumpsumRoute
  NpsRoute: typeof NpsRoute
  PpfRoute: typeof PpfRoute
  PrivacyRoute: typeof PrivacyRoute
  RdRoute: typeof RdRoute
  SipRoute: typeof SipRoute
  TaxRoute: typeof TaxRoute
  TermsRoute: typeof TermsRoute
  BlogsBuyHomeVsRentIndia2026Route: typeof BlogsBuyHomeVsRentIndia2026Route
  BlogsOldVsNewTaxRegime2026CompleteGuideRoute: typeof BlogsOldVsNewTaxRegime2026CompleteGuideRoute
  BlogsSipVsEmiVsFdRoute: typeof BlogsSipVsEmiVsFdRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emi': {
      id: '/emi'
      path: '/emi'
      fullPath: '/emi'
      preLoaderRoute: typeof EmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fd': {
      id: '/fd'
      path: '/fd'
      fullPath: '/fd'
      preLoaderRoute: typeof FdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lumpsum': {
      id: '/lumpsum'
      path: '/lumpsum'
      fullPath: '/lumpsum'
      preLoaderRoute: typeof LumpsumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nps': {
      id: '/nps'
      path: '/nps'
      fullPath: '/nps'
      preLoaderRoute: typeof NpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppf': {
      id: '/ppf'
      path: '/ppf'
      fullPath: '/ppf'
      preLoaderRoute: typeof PpfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rd': {
      id: '/rd'
      path: '/rd'
      fullPath: '/rd'
      preLoaderRoute: typeof RdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sip': {
      id: '/sip'
      path: '/sip'
      fullPath: '/sip'
      preLoaderRoute: typeof SipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/buy-home-vs-rent-india-2026': {
      id: '/blogs/buy-home-vs-rent-india-2026'
      path: '/blogs/buy-home-vs-rent-india-2026'
      fullPath: '/blogs/buy-home-vs-rent-india-2026'
      preLoaderRoute: typeof BlogsBuyHomeVsRentIndia2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/old-vs-new-tax-regime-2026-complete-guide': {
      id: '/blogs/old-vs-new-tax-regime-2026-complete-guide'
      path: '/blogs/old-vs-new-tax-regime-2026-complete-guide'
      fullPath: '/blogs/old-vs-new-tax-regime-2026-complete-guide'
      preLoaderRoute: typeof BlogsOldVsNewTaxRegime2026CompleteGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/sip-vs-emi-vs-fd': {
      id: '/blogs/sip-vs-emi-vs-fd'
      path: '/blogs/sip-vs-emi-vs-fd'
      fullPath: '/blogs/sip-vs-emi-vs-fd'
      preLoaderRoute: typeof BlogsSipVsEmiVsFdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EmiRoute: EmiRoute,
  FdRoute: FdRoute,
  LumpsumRoute: LumpsumRoute,
  NpsRoute: NpsRoute,
  PpfRoute: PpfRoute,
  PrivacyRoute: PrivacyRoute,
  RdRoute: RdRoute,
  SipRoute: SipRoute,
  TaxRoute: TaxRoute,
  TermsRoute: TermsRoute,
  BlogsBuyHomeVsRentIndia2026Route: BlogsBuyHomeVsRentIndia2026Route,
  BlogsOldVsNewTaxRegime2026CompleteGuideRoute:
    BlogsOldVsNewTaxRegime2026CompleteGuideRoute,
  BlogsSipVsEmiVsFdRoute: BlogsSipVsEmiVsFdRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
